### ISSUE TITLE
Clock doesn't start

### ISSUE THREAD

**Issue by dragonnice01** [johniak/word-clock#7]
Hi,
I installed everything as described but get the following error:

sudo python3 src/wordclock/main.py --pin D12 --brightness 0.5 --gif ../../heart-art.gif
Traceback (most recent call last):
  File "/home/marcusthurand/word-clock-main/raspberry-pi/src/wordclock/main.py", line 3, in <module>
    from clock_display_hal import ClockDisplayHAL
  File "/home/marcusthurand/word-clock-main/raspberry-pi/src/wordclock/clock_display_hal.py", line 1, in <module>
    import board
ModuleNotFoundError: No module named 'board'

is there something wrong with the python installation?
Thx

**Comment by johniak** [comment]
Thanks, for the input I will try to fix this issue :)
